name: HepG2_WGBS
random_state: 1234
seqdata:
  add_rev_comp: false
  alphabet: DNA
  batch_size: 10000
  bw_names:
  - CpG_methylation_coverage_rep1
  - CpG_sites_coverage_rep1
  bws:
  - /cellar/users/aklie/data/datasets/SeqDatasets/HepG2_WGBS/processed/HepG2_WGBS_CpG_methylation_coverage_rep1.bigWig
  - /cellar/users/aklie/data/datasets/SeqDatasets/HepG2_WGBS/processed/ENCFF782HWK_HepG2_WGBS_CpG_sites_coverage_rep1.bigWig
  cov_var: cov
  fasta: /cellar/users/aklie/data/ref/genomes/hg38/hg38.fa
  fixed_length: 5000
  loci: /cellar/users/aklie/data/ref/genomes/hg38/windows/hg38.100kb_windows.bed
  max_jitter: 0
  seq_var: seq
  target_length: 5000
  upper_case: false
splits: /cellar/users/aklie/projects/ML4GLand/tutorials/data/splits/ENCODE_cross-val.json
threads: 4
